apiVersion: batch/v1
kind: Job
metadata:
  name: java-app
  namespace: java-app
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: java-app
        image: pravin8702/java-app:v3
